site_name: Test docs
site_description: 'A docs test'
site_author: 'Kjell Hedström'
docs_dir: docs/
repo_name: 'KjellKod/g3log'
repo_url: 'https://github.com/KjellKod/g3log'
nav:
    - Home: index.md
theme:
  name: 'material'
